### ISSUE TITLE
Unable to scan project

### ISSUE THREAD

**Issue by lukasvopelka** [kdgregory/pomutil#8]
Attempt to run dependency check ends with:

`Exception in thread "main" org.apache.bcel.classfile.ClassFormatException: Invalid byte tag in constant pool: 18
	at org.apache.bcel.classfile.Constant.readConstant(Constant.java:146)
	at org.apache.bcel.classfile.ConstantPool.<init>(ConstantPool.java:67)
	at org.apache.bcel.classfile.ClassParser.readConstantPool(ClassParser.java:222)
	at org.apache.bcel.classfile.ClassParser.parse(ClassParser.java:136)
	at com.kdgregory.pomutil.dependency.ClassScanner.processStream(ClassScanner.java:111)
	at com.kdgregory.pomutil.dependency.ClassScanner.processTreeOrFile(ClassScanner.java:101)
	at com.kdgregory.pomutil.dependency.ClassScanner.processTreeOrFile(ClassScanner.java:95)
	at com.kdgregory.pomutil.dependency.ClassScanner.processTreeOrFile(ClassScanner.java:95)
	at com.kdgregory.pomutil.dependency.ClassScanner.processTreeOrFile(ClassScanner.java:95)
	at com.kdgregory.pomutil.dependency.ClassScanner.processTreeOrFile(ClassScanner.java:95)
	at com.kdgregory.pomutil.dependency.ClassScanner.processTreeOrFile(ClassScanner.java:95)
	at com.kdgregory.pomutil.dependency.ClassScanner.<init>(ClassScanner.java:57)
	at com.kdgregory.pomutil.dependency.DependencyCheck.selectReferencedClasses(DependencyCheck.java:206)
	at com.kdgregory.pomutil.dependency.DependencyCheck.run(DependencyCheck.java:101)
	at com.kdgregory.pomutil.dependency.Main.main(Main.java:27)
`

**Comment by kdgregory** [comment]
@lukasvopelka  - what version of Java are you using? I'm guessing later than 8, and I'll need to check if there's a newer version of BCEL that will support that.

**Comment by kdgregory** [comment]
Also, I think that the Maven dependency check be a better option: I originally wrote this when Maven didn't do a very good job at determining which dependencies were used or not. However, it's been updated in the interim (and this project hasn't).

**Comment by lukasvopelka** [comment]
I tried JDK 8 and JDK 11 with no luck .. anyway I already did what I needed using native Maven functionalities.. thanks for your reply ..
